[project]
name = "pic-queuer"
version = "0.2.0"
description = "Screenshot Utility for Windows"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=10.0.0",
    "pyinstaller>=6.16.0",
    "pyperclip>=1.8.2",
    "pyqt6>=6.4.0",
]
